# Morphological Transformations

### 1. Erosion


In [1]:
import cv2
import numpy as np

In [50]:
img = cv2.imread('j1.png',0)
kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(img,kernel,iterations = 1)

In [49]:
cv2.imshow('erosion',erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 2. Dilation

In [51]:
dilation = cv2.dilate(img,kernel,iterations = 1)

In [52]:
cv2.imshow('dilation',dilation)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 3. Opening

In [20]:
opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)

In [33]:
cv2.imshow('opening',opening)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 4. Closing

In [31]:
closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)

In [34]:
cv2.imshow('closing',closing)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 5. Morphological Gradient

In [ ]:
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)

In [ ]:
cv2.imshow('gradient',gradient)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 6. Top Hat

In [39]:
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel)

In [46]:
cv2.imshow('tophat',tophat)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 7. Black Hat

In [42]:
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel)

In [45]:
cv2.imshow('blackhat',blackhat)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Structuring Element

In [22]:
# Rectangular Kernel
cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [23]:
# Elliptical Kernel
cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))

array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0]], dtype=uint8)

In [24]:
# Cross-shaped Kernel
cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=uint8)